# Twenty individuals. Sex x age band x days-per-week across 3/4/5/6, plus a real constraint each.
#
# The constraint is the point of this batch. A note like "prior disc irritation" has to change what is on
# the page -- an exercise removed, a substitute chosen, and one movement put on a deliberately slower
# progression -- or it is decoration. Each person records what was changed and why.

PEOPLE = [
 # ---- MALE 20-30 -------------------------------------------------------------------------------------
 dict(n=1,  name="Marcus",  sex="M", age="20–30", days=3, weeks=4,
      note="Golfer's elbow flare 8 months ago from heavy barbell curls. Fine now, but aches for a day after direct arm work with a straight bar.",
      changed="Straight-bar curls out entirely. Everything for biceps is neutral or supinating grip (hammer, incline dumbbell). Arm work is rep-first only — no load jumps on a tendon with a history.",
      slow="Hammer Curl"),
 dict(n=2,  name="Deshawn", sex="M", age="20–30", days=4, weeks=6,
      note="Left AC joint clicks and aches on flat barbell benching, worse at lockout. No pain on incline or dumbbells.",
      changed="No flat barbell press anywhere in the block. Pressing is incline dumbbell and Smith incline — both let the shoulder blade move and neither locks the hands to one bar path. Fly work is mid-height, not high.",
      slow="Incline Smith Press"),
 dict(n=3,  name="Tobias",  sex="M", age="20–30", days=5, weeks=6,
      note="Two lower-back episodes in the last two years, both from deadlifting off the floor when tired. Nothing since. No symptoms currently.",
      changed="No conventional deadlift. Hinging is RDL from a rack and cable pull-through — both keep the axial load lower and neither starts from the floor. Squat is Smith so the bar path is fixed when he fatigues. G61 applies twice over: six weeks and a spine history.",
      slow="Barbell RDL"),
 dict(n=4,  name="Owen",    sex="M", age="20–30", days=6, weeks=6,
      note="Chronic wrist stiffness both sides, worse in extension. Straight-bar front squats and flat-palm pressing bother it.",
      changed="No barbell front rack anywhere. Pressing is dumbbell or machine so the wrist can sit neutral. Triceps work is rope, not straight bar.",
      slow="Chest Press Machine"),
 dict(n=5,  name="Rhys",    sex="M", age="20–30", days=4, weeks=4,
      note="Nothing structural — first structured block. Very deconditioned, hasn't trained in three years.",
      changed="Rep ranges start at the top of every band, not the bottom. Sets capped at three everywhere for the first block regardless of what the exercise would normally take. Progression is rep-first on everything, including compounds — load moves only once the range is topped out twice.",
      slow=None),
 # ---- MALE 30-40 -------------------------------------------------------------------------------------
 dict(n=6,  name="Callum",  sex="M", age="30–40", days=3, weeks=6,
      note="Right rotator cuff tendinopathy diagnosed 2 years ago. Manageable. Overhead pressing above eye level is the one thing that reliably aggravates it.",
      changed="No overhead press. Shoulders are built from lateral raises and a landmine press that stays below eye level. Incline pressing is capped at 30 degrees.",
      slow="Dumbbell Lateral Raise"),
 dict(n=7,  name="Priyan",  sex="M", age="30–40", days=4, weeks=6,
      note="Left knee ACL reconstruction 6 years ago. Full function, but deep loaded flexion under fatigue makes it ache the next day.",
      changed="Squat depth capped at parallel and done on the Smith so depth is repeatable. No walking lunges. Single-leg work is split squats with a fixed rear foot, not step-ups. Quad volume leans on leg press and extensions where the shear is lower.",
      slow="Smith Machine Squat"),
 dict(n=8,  name="Grant",   sex="M", age="30–40", days=5, weeks=6,
      note="Pec strain 14 months ago on a heavy dumbbell press, felt it at the bottom of the range. Healed, but nervous in a deep stretch.",
      changed="No deep-stretch dumbbell pressing in the first block. Pressing is Smith and machine where the bottom is bounded, plus cable flies at mid-height where he controls the range. Dumbbell pressing returns next block if this one runs clean.",
      slow="Incline Smith Press"),
 dict(n=9,  name="Wes",     sex="M", age="30–40", days=6, weeks=6,
      note="Cervical tension and headaches after heavy shrugs and upright rows. No imaging, no diagnosis.",
      changed="No shrugs, no upright rows. Trap work comes from rows and carries rather than direct shrugging. Rear delt work is chest-supported so the neck isn't stabilising.",
      slow=None),
 dict(n=10, name="Ivan",    sex="M", age="30–40", days=3, weeks=4,
      note="Plantar fasciitis in the right foot, currently symptomatic in the mornings.",
      changed="No standing calf raises — the loaded dorsiflexion is the aggravator. Calves are seated only. Nothing barefoot, nothing plyometric. Leg work is machine-based so he isn't standing under load for long.",
      slow="Seated Calf Raise"),
 # ---- FEMALE 20-30 -----------------------------------------------------------------------------------
 dict(n=11, name="Sofia",   sex="F", age="20–30", days=3, weeks=4,
      note="Anterior knee pain (patellofemoral) with deep flexion and going downstairs. Worse in the last two months.",
      changed="No deep squatting, no lunges. Quads are built from leg press with a high foot position and leg extensions in the top half of the range only. Glute work is hinge and thrust dominant, which she tolerates fine.",
      slow="Leg Extension"),
 dict(n=12, name="Amara",   sex="F", age="20–30", days=4, weeks=6,
      note="Hip impingement on the right — a pinch at the front of the hip below about parallel.",
      changed="Squat depth capped above the pinch and stance widened. Hip thrusts and RDLs do the heavy glute work since neither goes near end-range flexion. No deep leg press.",
      slow="Barbell Hip Thrust"),
 dict(n=13, name="Nell",    sex="F", age="20–30", days=5, weeks=6,
      note="Hamstring strain 5 months ago, high on the left. Cleared, but still feels it at end range on RDLs.",
      changed="RDL range shortened to just above where it pulls, and it runs on the slow track all block. Leg curls do the hamstring volume instead, since the knee-flexion pattern doesn't load the strained tissue at length.",
      slow="Barbell RDL"),
 dict(n=14, name="Bea",     sex="F", age="20–30", days=6, weeks=6,
      note="Hypermobile — no injury history but joints sit at end range easily and she's been told to avoid locking out.",
      changed="Everything is machine or cable where the range is bounded. No barbell lockouts. Rep ranges sit higher across the board so load stays lower for the same stimulus. Tempo is controlled rather than loaded heavy.",
      slow=None),
 dict(n=15, name="Junia",   sex="F", age="20–30", days=4, weeks=4,
      note="Nothing structural. Returning after 6 months off, previously trained 3 years.",
      changed="Volume starts at two thirds of what she previously handled and the block is four weeks, not six — the point is re-exposure, not accumulation. Rep ranges start high.",
      slow=None),
 # ---- FEMALE 30-40 -----------------------------------------------------------------------------------
 dict(n=16, name="Marisol", sex="F", age="30–40", days=3, weeks=6,
      note="Post-partum 11 months. Cleared to train. Some coning at the midline on direct flexion work.",
      changed="No crunches, no sit-ups, no hanging leg raises. Core is anti-extension and anti-rotation only — dead bugs, Pallof, carries. Intra-abdominal load kept low, so no heavy bracing under a bar.",
      slow=None),
 dict(n=17, name="Tanvi",   sex="F", age="30–40", days=4, weeks=6,
      note="Bicep tendon irritation at the front of the right shoulder. Aggravated by wide-grip pulling and deep dips.",
      changed="No wide-grip pulldowns, no dips. Pulling is neutral grip throughout. Bicep work is limited and neutral. Pressing is machine so the shoulder isn't stabilising a free weight.",
      slow="Lat Pulldown"),
 dict(n=18, name="Renata",  sex="F", age="30–40", days=5, weeks=6,
      note="Osteoarthritis in the left knee, diagnosed. Good days and bad days. Warms up out of it but stiff to start.",
      changed="Longer warm-up ramp on every leg exercise — three rungs instead of one. No deep flexion, no impact. Load progresses on the slow track for anything knee-dominant, and rep ranges sit high to keep joint load down.",
      slow="Leg Press"),
 dict(n=19, name="Camille", sex="F", age="30–40", days=6, weeks=6,
      note="Sciatic symptoms down the right leg when she hinges under fatigue. Nothing at rest.",
      changed="Hinging is limited to hip thrusts and cable pull-throughs — both keep the spine out of it. No RDLs, no good mornings, no bent rows. Rows are chest-supported.",
      slow="Cable Pull-Through"),
 dict(n=20, name="Elin",    sex="F", age="30–40", days=3, weeks=4,
      note="Ankle sprain 4 months ago, right side. Dorsiflexion still limited compared to the left.",
      changed="Heel elevation on all squatting so the limited ankle isn't the constraint. No standing calf work on that side until range returns — seated only. Single-leg work is stable (split squat), not balance-dependent.",
      slow="Smith Machine Squat"),
]
